/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import usuario.Usuario;
import view.telasCliente.ExibirCliente;
import view.telasFornecedor.ExibirFornecedor;
import view.telasProduto.ExibirProduto;
import view.telasVenda.ExibirVenda;

/**
 *
 * @author Pichau
 */
public class TelaInicialVIEW extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     * @param usuario
     */
    public TelaInicialVIEW(Usuario usuario) {
        initComponents();
        exibeSaudacao(usuario);
        configurarPermissoes(usuario);
    }

//    TelaInicialVIEW(Usuario usuario) {
//        exibeSaudacao(usuario);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBoasVindas = new javax.swing.JLabel();
        btnFornecedoresVIEW = new javax.swing.JButton();
        btnProdutosVIEW = new javax.swing.JButton();
        btnClientesVIEW = new javax.swing.JButton();
        btnVendasVIEW = new javax.swing.JButton();
        btnCaixaVIEW = new javax.swing.JButton();
        btnRelatorioVIEW = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        lblTituloSistema = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblBoasVindas.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblBoasVindas.setForeground(new java.awt.Color(9, 16, 87));
        lblBoasVindas.setText("Bem-vindo, Usuário! Sua permissão é gerente. ");

        btnFornecedoresVIEW.setBackground(new java.awt.Color(2, 76, 170));
        btnFornecedoresVIEW.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnFornecedoresVIEW.setForeground(new java.awt.Color(255, 255, 255));
        btnFornecedoresVIEW.setText("Fornecedores");
        btnFornecedoresVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedoresVIEWActionPerformed(evt);
            }
        });

        btnProdutosVIEW.setBackground(new java.awt.Color(2, 76, 170));
        btnProdutosVIEW.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnProdutosVIEW.setForeground(new java.awt.Color(255, 255, 255));
        btnProdutosVIEW.setText("Produtos");
        btnProdutosVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosVIEWActionPerformed(evt);
            }
        });

        btnClientesVIEW.setBackground(new java.awt.Color(2, 76, 170));
        btnClientesVIEW.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnClientesVIEW.setForeground(new java.awt.Color(255, 255, 255));
        btnClientesVIEW.setText("Clientes");
        btnClientesVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesVIEWActionPerformed(evt);
            }
        });

        btnVendasVIEW.setBackground(new java.awt.Color(2, 76, 170));
        btnVendasVIEW.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnVendasVIEW.setForeground(new java.awt.Color(255, 255, 255));
        btnVendasVIEW.setText("Vendas");
        btnVendasVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasVIEWActionPerformed(evt);
            }
        });

        btnCaixaVIEW.setBackground(new java.awt.Color(2, 76, 170));
        btnCaixaVIEW.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnCaixaVIEW.setForeground(new java.awt.Color(255, 255, 255));
        btnCaixaVIEW.setText("Caixa");
        btnCaixaVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaVIEWActionPerformed(evt);
            }
        });

        btnRelatorioVIEW.setBackground(new java.awt.Color(2, 76, 170));
        btnRelatorioVIEW.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnRelatorioVIEW.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorioVIEW.setText("Relatório");
        btnRelatorioVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioVIEWActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(238, 238, 238));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Logo2_1.png"))); // NOI18N

        lblTituloSistema.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblTituloSistema.setForeground(new java.awt.Color(9, 16, 87));
        lblTituloSistema.setText("Sistema de Produtos de Beleza");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logo)
                .addGap(121, 121, 121)
                .addComponent(lblTituloSistema)
                .addContainerGap(708, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTituloSistema)
                        .addGap(57, 57, 57))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoasVindas)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnProdutosVIEW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFornecedoresVIEW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClientesVIEW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVendasVIEW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCaixaVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorioVIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lblBoasVindas)
                .addGap(73, 73, 73)
                .addComponent(btnFornecedoresVIEW)
                .addGap(18, 18, 18)
                .addComponent(btnProdutosVIEW)
                .addGap(18, 18, 18)
                .addComponent(btnClientesVIEW)
                .addGap(18, 18, 18)
                .addComponent(btnVendasVIEW)
                .addGap(18, 18, 18)
                .addComponent(btnCaixaVIEW)
                .addGap(18, 18, 18)
                .addComponent(btnRelatorioVIEW)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFornecedoresVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresVIEWActionPerformed
        ExibirFornecedor fornecedores = new ExibirFornecedor();
        fornecedores.setVisible(true);
    }//GEN-LAST:event_btnFornecedoresVIEWActionPerformed

    private void btnProdutosVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosVIEWActionPerformed
        ExibirProduto produtos = new ExibirProduto();
        produtos.setVisible(true);
    }//GEN-LAST:event_btnProdutosVIEWActionPerformed

    private void btnClientesVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesVIEWActionPerformed
        ExibirCliente clientes = new ExibirCliente();
        clientes.setVisible(true);
    }//GEN-LAST:event_btnClientesVIEWActionPerformed

    private void btnVendasVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasVIEWActionPerformed
        ExibirVenda vendas = new ExibirVenda();
        vendas.setVisible(true);
    }//GEN-LAST:event_btnVendasVIEWActionPerformed

    private void btnCaixaVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaVIEWActionPerformed
        CaixaVIEW caixa = new CaixaVIEW();
        caixa.setVisible(true);
    }//GEN-LAST:event_btnCaixaVIEWActionPerformed

    private void btnRelatorioVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioVIEWActionPerformed
        RelatorioVIEW relatorioView = new RelatorioVIEW();
        relatorioView.setVisible(true);
    }//GEN-LAST:event_btnRelatorioVIEWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private Usuario usuario;
            public void run() {
                new TelaInicialVIEW(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixaVIEW;
    private javax.swing.JButton btnClientesVIEW;
    private javax.swing.JButton btnFornecedoresVIEW;
    private javax.swing.JButton btnProdutosVIEW;
    private javax.swing.JButton btnRelatorioVIEW;
    private javax.swing.JButton btnVendasVIEW;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBoasVindas;
    private javax.swing.JLabel lblTituloSistema;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables

    private void exibeSaudacao(Usuario usuario) {
        String boasVindas = "Bem-vindo, " + usuario.getNome()+ "! Sua permissão é " + usuario.getTipo();
        lblBoasVindas.setText(boasVindas);
    }
    
    private void configurarPermissoes(Usuario usuarioLogado) {
        if (usuarioLogado == null) return;
        
        String tipo = usuarioLogado.getTipo();
        
        switch (tipo.toLowerCase()) {
            case "gerente":
                break;

            case "atendente":
                btnCaixaVIEW.setEnabled(false);
                btnFornecedoresVIEW.setEnabled(false);
                btnRelatorioVIEW.setEnabled(false);
                break;

            case "financeiro":
                btnClientesVIEW.setEnabled(false);
                btnProdutosVIEW.setEnabled(false);
                btnVendasVIEW.setEnabled(false);
                btnRelatorioVIEW.setEnabled(false);
                break;
            default:
                break;
        }
    }
}
